channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bioconductor-ebimage
- bioconductor-biocgenerics
- openjdk=11
- r-assertthat
# https://github.com/ContinuumIO/anaconda-issues/issues/4656
- r-base=4.1.3
- r-devtools
- r-httr
- r-irdisplay
- r-irkernel
- r-jpeg
- r-repr
- r-rjava
- r-roxygen2
- r-testthat
- r-tidyverse
- r-xml2
- r-getpass

